# image: tapis/tenants-api-migrations
from tapis/tenants-api

COPY migrations /home/tapis/migrations

ENV MIGRATIONS_RUNNING=True

User root
RUN chown -R tapis:tapis /home/tapis
USER tapis

ENTRYPOINT ["flask", "db"]