---

version: "3.5"


networks:
    tenants:
        driver: bridge


volumes:
    pgdata:

    pgadmindata:


services:
    postgres:
        image: postgres:9.4
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - tenants
        environment:
            POSTGRES_HOST_AUTH_METHOD: "trust"

    migrations:
        image: tapis/tenants-api-migrations
        volumes:
            - ./config-local.json:/home/tapis/config.json
        networks:
            - tenants
        depends_on:
            - postgres

    tenants:
        image: tapis/tenants-api:latest
        ports:
            - "5000:5000"
        volumes:
            - ./config-local.json:/home/tapis/config.json
            - ./service.log:/home/tapis/service.log
        networks:
            - tenants
        depends_on:
            - postgres

    tenants-tests:
        image: tapis/tenants-api-tests
        networks:
            - tenants
        volumes:
            - ./config-local.json:/home/tapis/config.json

    pgadmin:
        image: dpage/pgadmin4
        environment:
          PGADMIN_DEFAULT_EMAIL: "admin@test.com"
          PGADMIN_DEFAULT_PASSWORD: "password"
        ports:
            - "8000:80"
        networks:
            - tenants
        depends_on:
          - postgres
        volumes:
            - pgadmindata:/var/lib/pgadmin